### ISSUE TITLE
is there pth supplied?

### ISSUE THREAD

**Issue by mengzhibin** [sunggukcha/deeplabs#1]
it would be very nice if there is parameters supplied.

**Comment by sunggukcha** [comment]
You can reproduce them almost just the way they are because I have trained them with fixed random seed.
I will look for a way to distribute the parameters. Please wait kindly, thanks.

**Comment by sunggukcha** [comment]
Parameters are updated.

**Comment by SAIVENKATARAJU** [comment]
Hi,

i just downloaded parameters using wget https://www.dropbox.com/s/dw9hmcumrothvi9/ign101.pth.tar?dl=0. but i am unable to unzip them. "file filename" command showing as data.  If i manually download and try to extract, its showing not an archive
