### ISSUE TITLE
would you mind share test command?

### ISSUE THREAD

**Issue by fuweifuvtoo** [sunggukcha/deeplabs#2]
would you mind share test command?
eg:
python evaluate.py --model xx ...

**Comment by sunggukcha** [comment]
Hello fuweifu-vtoo,

I used shell script.
```
clear
bs=1

backbone='resnet'
dataset='bdd'
model='deeplabv3+'
norm='gn'
save_dir='./prd'
resume='/checkpoint/dir/here'

rm -rf $save_dir
mkdir $save_dir

python evaluate.py --backbone $backbone --dataset $dataset --model $model --norm $norm --save-dir $save_dir --batch-size $bs --resume $resume --test
```
Saving such code as **go_eval.sh**, 
`bash go_eval.sh` works.

I recommend you to look up arguments in evaluate.py.

Hope it helps,
Sungguk

**Comment by SAIVENKATARAJU** [comment]
Hi @fuweifu-vtoo 

Are you able to generate the output? can you please help me. i tried with 500 test images but in prd folder getting all blank images

looking forward for your reply

**Comment by fuweifu-vtoo** [comment]
hi @SAIVENKATARAJU 
use this script

`import os
import numpy as np
from PIL import Image
import cv2

trainid_label_dir = r'path1'
color_label_dir = r"path2"
if not os.path.exists(color_label_dir):
    os.mkdir(color_label_dir)

palette = [0,   0,   0,
         255,   0,   0, 
           0,   0, 255, 
           0, 255,   0,  
         255, 255,   0, 
           0, 255, 255,
         255,   0, 255,
         200, 100, 200]

zero_pad = 256 * 3 - len(palette)
for i in range(zero_pad):
    palette.append(0)

def function_label(x):
    return x

def colorize_mask(mask):
    new_mask = mask.convert('P')
    new_mask.putpalette(palette)
    return new_mask

def trainid2color():
    filename_list = [x for x in os.listdir(trainid_label_dir) if '.png' in x]
    filename_list.sort()
    for filename in filename_list:
        trainid_label_name = os.path.join(trainid_label_dir, filename)
        color_label_name = os.path.join(color_label_dir, filename)
        print("Parse %s" % (filename))
        trainid_label = Image.open(trainid_label_name)
        trainid_label = trainid_label.convert("L")
        trainid_label = trainid_label.point(function_label)
        
        color_label = colorize_mask(trainid_label)
        color_label.save(color_label_name)

if __name__ == '__main__':
	trainid2color()
`

**Comment by fuweifuvtoo** [comment]
hi @SAIVENKATARAJU 
use this script
```
import os
import numpy as np
from PIL import Image
import cv2

trainid_label_dir = r'D:\camera_0717\images_labelme_json'
color_label_dir = r"C:\Users\ryanwfu\Desktop\resnet152_prd_bdd_color"
if not os.path.exists(color_label_dir):
    os.mkdir(color_label_dir)

palette = [0,   0,   0,
         255,   0,   0, 
           0,   0, 255, 
           0, 255,   0,  
         255, 255,   0, 
           0, 255, 255,
         255,   0, 255,
         200, 100, 200]

zero_pad = 256 * 3 - len(palette)
for i in range(zero_pad):
    palette.append(0)

def function_label(x):
    return x

def colorize_mask(mask):
    new_mask = mask.convert('P')
    new_mask.putpalette(palette)
    return new_mask

def trainid2color():
    filename_list = [x for x in os.listdir(trainid_label_dir) if '.png' in x]
    filename_list.sort()
    for filename in filename_list:
        trainid_label_name = os.path.join(trainid_label_dir, filename)
        color_label_name = os.path.join(color_label_dir, filename)
        print("Parse %s" % (filename))
        trainid_label = Image.open(trainid_label_name)
        trainid_label = trainid_label.convert("L")
        trainid_label = trainid_label.point(function_label)
        
        color_label = colorize_mask(trainid_label)
        color_label.save(color_label_name)

if __name__ == '__main__':
	trainid2color()
```
