### ISSUE TITLE
Doubt: In experiment and results, you have provides links to parameters. is this paramenters trained on BDD100k dataset?

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [sunggukcha/deeplabs#4]

**Comment by sunggukcha** [comment]
Yes, the parameters are of ResNet/DeepLab V3+ and are trained on BDD100k drivable area segmentation. 
Which issue or doubt do you have?

**Comment by SAIVENKATARAJU** [comment]
Hey thanks for quick reply. I just want to know whether I can use that parameters for quick test on a random image to detect drivable areas

**Comment by sunggukcha** [comment]
You can use them. 
I have tested them on random images including driving scenes in youtube and BDD100k videos.
Samples on BDD100k videos: https://www.youtube.com/watch?v=-dzS8VlVmk4&list=PLn3JZxvQvVuAbhz5ep4X-dysT9jLMMQpv
You should consider many things. Good  luck.
