### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'backbone'

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [sunggukcha/deeplabs#6]
while i am trying to test on different random images using stack.py, i am getting the following error

``python stack.py  --dataset=/home/ubuntu/deeplabs/images/  --batch_size=1``

``Found 1 images
Traceback (most recent call last):
  File "stack.py", line 173, in <module>
    stack = Stack(args)
  File "stack.py", line 94, in __init__
    freeze_bn=False)
TypeError: __init__() got an unexpected keyword argument 'backbone'``

**Comment by sunggukcha** [comment]
I am sharing `stack.py` for final ensemble of various models, which improves the performance.
If you do not understand the script, I recommend you to use `evaluate.py` instead.

**Comment by SAIVENKATARAJU** [comment]
Hi Thanks for your reply.

I am having hard times to test on single image(not in bdd100k) as i am new to pytorch. can you please provide steps to test on single image. 

Thanks in advance

**Comment by sunggukcha** [comment]
#2 
It will help you.
